Feature/remove matero extentions
peopleware/angular-sdk pull request #20
Opened 2024-10-07 13:52 UTC by MarkCuypersPpw

2024-10-07 14:02 UTC, glenstaes requested changes

2024-10-07 14:02 UTC, glenstaes commented on projects/ppwcode/ng-common-components/src/lib/loader/loader.component.ts
> +    imports: [MatProgressBar, NgClass],
`NgClass` can be removed.

2024-10-07 14:02 UTC, glenstaes commented on projects/ppwcode/ng-common-components/src/lib/table/table.component.scss
>          padding-right: 16px;
I think the right padding was for the possible scrollbar. Why the left padding?

2024-10-08 08:43 UTC, MarkCuypersPpw commented on projects/ppwcode/ng-common-components/src/lib/loader/loader.component.scss
> +        height: 4px;
ik hou het bij var(--mdc-linear-progress-active-indicator-height);
een progressbar nog dikker maken lijkt me niet mooi

2024-10-08 09:09 UTC, glenstaes approved these changes

2024-10-08 09:11 UTC, merged